# Generated by Django 5.0.6 on 2024-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0003_fornecedor_quantidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedor",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
    ]
