# Generated by Django 5.1 on 2024-08-29 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0004_remove_fornecedor_quantidade_produto_quantidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedor",
            name="endereco",
        ),
        migrations.AddField(
            model_name="produto",
            name="fornecedor",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to="loja.fornecedor",
            ),
        ),
    ]
